print instructive message instead of error message after `cheat -l` when there is no cheetsheet
If there's no cheatsheets,
```bash
ValueError: max() arg is an empty sequence
```
is thrown while calculating `pad_length` in function `list` in cheat/sheets.py

This commit prints a message
```bash
No cheatsheets yet. Create and edit by `cheat -e <your-cheatsheet>`.
```
instead of the raw error message.